### ISSUE TITLE
[Setting] 서버 DB 연결

### ISSUE THREAD

**Issue by Chaeniiiii** [KKWJ-DGU/FoDong-SERVER#13]
## 🔥 Issue 내용
-  서버 DB 연결

## ✅ To-do
- [x] 서버 DB 정보 작성 후 암호화
- [x] DB 테이블 생성
- [x] DB와 함께 배포
