### ISSUE TITLE
[Refactor] 식당 , 카테고리 도메인 단위 테스트

### ISSUE THREAD

**Issue by Chaeniiiii** [KKWJ-DGU/FoDong-SERVER#50]
## 🔥 Issue 내용
- 식당 도메인 테스트 코드 리팩토링

## ✅ To-do
- [ ] 랜덤 식당 리스트 조회 테스트 코드
- [ ] 카테고리 별 식당 리스트 조회 테스트 코드 
- [ ] 식당 정보 조회  테스트 코드
- [ ] 랜덤 식당 추천 테스트 코드
- [ ] 검색 식당 조회 테스트 코드
- [ ] 카테고리 리스트 조회 테스트 코드
