### ISSUE TITLE
[Fix] Response Type 변경 

### ISSUE THREAD

**Issue by Chaeniiiii** [KKWJ-DGU/FoDong-SERVER#75]
## 🔥 Issue 내용
Response Type 변경 

## ✅ To-do
- [x] 식당 Response Type 변경
- [x] 카테고리 Response Type 변경
- [x] 위시리스트 Response Type 변경
